# Generated by Django 5.0.7 on 2026-01-18 22:10

import apps.bookings.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_reference', models.CharField(default=apps.bookings.models.generate_booking_reference, max_length=50, unique=True, verbose_name='Booking Reference')),
                ('pickup_address', models.CharField(max_length=500, verbose_name='Pickup Address')),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Pickup Latitude')),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Pickup Longitude')),
                ('pickup_notes', models.TextField(blank=True, verbose_name='Pickup Notes')),
                ('dropoff_address', models.CharField(max_length=500, verbose_name='Dropoff Address')),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Dropoff Latitude')),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Dropoff Longitude')),
                ('dropoff_notes', models.TextField(blank=True, verbose_name='Dropoff Notes')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('pickup_time', models.TimeField(verbose_name='Pickup Time')),
                ('num_passengers', models.PositiveIntegerField(verbose_name='Number of Passengers')),
                ('num_large_luggage', models.PositiveIntegerField(default=0, verbose_name='Large Luggage')),
                ('num_small_luggage', models.PositiveIntegerField(default=0, verbose_name='Small Luggage')),
                ('has_children', models.BooleanField(default=False, verbose_name='Has Children')),
                ('children_ages', models.JSONField(blank=True, default=list, help_text='List of children ages', verbose_name='Children Ages')),
                ('vehicle_upgrade_reason', models.TextField(blank=True, verbose_name='Upgrade Reason')),
                ('flight_number', models.CharField(blank=True, max_length=20, verbose_name='Flight Number')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('pricing_type', models.CharField(choices=[('fixed_route', 'Fixed Route'), ('distance_based', 'Distance Based')], max_length=20, verbose_name='Pricing Type')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance (km)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Price')),
                ('seasonal_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Seasonal Multiplier')),
                ('vehicle_class_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Vehicle Class Multiplier')),
                ('passenger_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Passenger Multiplier')),
                ('time_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Time Multiplier')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('extra_fees_json', models.JSONField(blank=True, default=list, help_text='JSON array of applied fees', verbose_name='Extra Fees')),
                ('extra_fees_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Extra Fees Total')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Final Price')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Customer Phone')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20, verbose_name='Payment Status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Payment Intent ID')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('actual_vehicle_class', models.ForeignKey(blank=True, help_text='May differ if upgraded', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_actual', to='vehicles.vehicleclass', verbose_name='Actual Vehicle Class')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer Account')),
                ('fixed_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='routes.fixedroute', verbose_name='Fixed Route')),
                ('selected_vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_selected', to='vehicles.vehicleclass', verbose_name='Selected Vehicle Class')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
