# Generated by Django 5.2 on 2026-01-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_round_trip',
            field=models.BooleanField(default=False, verbose_name='Is Round Trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Return Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_flight_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Return Flight Number'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Return Time'),
        ),
    ]
