# Generated by Django 5.0.7 on 2026-01-18 22:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_name', models.CharField(max_length=100, verbose_name='Fee Name')),
                ('fee_code', models.CharField(max_length=50, unique=True, verbose_name='Fee Code')),
                ('fee_type', models.CharField(choices=[('per_item', 'Per Item'), ('flat', 'Flat Fee'), ('percentage', 'Percentage')], default='flat', max_length=20, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in EUR (or percentage if fee_type=percentage)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount')),
                ('is_optional', models.BooleanField(default=True, help_text='User can opt-in/out', verbose_name='Optional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('applies_when', models.TextField(blank=True, help_text='Conditions for automatic application (JSON or description)', verbose_name='Applies When')),
            ],
            options={
                'verbose_name': 'Extra Fee',
                'verbose_name_plural': 'Extra Fees',
                'ordering': ['display_order', 'fee_name'],
            },
        ),
        migrations.CreateModel(
            name='PassengerMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_passengers', models.PositiveIntegerField(verbose_name='Min Passengers')),
                ('max_passengers', models.PositiveIntegerField(verbose_name='Max Passengers')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Multiplier')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Passenger Multiplier',
                'verbose_name_plural': 'Passenger Multipliers',
                'ordering': ['min_passengers'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_name', models.CharField(max_length=100, verbose_name='Season Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='1.00 = base price, 1.30 = +30%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Multiplier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('year_recurring', models.BooleanField(default=True, help_text='If true, repeats every year (ignores year in dates)', verbose_name='Year Recurring')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower = higher priority (for overlapping seasons)', verbose_name='Priority')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Seasonal Multiplier',
                'verbose_name_plural': 'Seasonal Multipliers',
                'ordering': ['priority', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_name', models.CharField(max_length=100, verbose_name='Time Period Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Multiplier')),
                ('applies_to_weekdays', models.BooleanField(default=True, verbose_name='Weekdays')),
                ('applies_to_weekends', models.BooleanField(default=True, verbose_name='Weekends')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Time Multiplier',
                'verbose_name_plural': 'Time Multipliers',
                'ordering': ['start_time'],
            },
        ),
    ]
