# Generated by Django 5.2 on 2026-01-19 14:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_add_vehicle_class_to_passenger_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundTripDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Round Trip Discount', max_length=100, verbose_name='Discount Name')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('0.90'), help_text='0.90 = 10% discount, 0.85 = 15% discount', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Multiplier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, help_text='Shown to customers', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Round Trip Discount',
                'verbose_name_plural': 'Round Trip Discounts',
            },
        ),
    ]
