# Generated by Django 5.0.7 on 2026-01-18 22:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistancePricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_name', models.CharField(max_length=255, verbose_name='Rule Name')),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Minimum charge for this tier', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Rate (EUR)')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per km (EUR)')),
                ('price_per_minute', models.DecimalField(decimal_places=2, default=0, help_text='Optional: for traffic-based pricing', max_digits=10, verbose_name='Price per minute (EUR)')),
                ('min_distance_km', models.PositiveIntegerField(default=0, verbose_name='Minimum Distance (km)')),
                ('max_distance_km', models.PositiveIntegerField(default=9999, help_text='Use 9999 for unlimited', verbose_name='Maximum Distance (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority', verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Distance Pricing Rule',
                'verbose_name_plural': 'Distance Pricing Rules',
                'ordering': ['priority', 'min_distance_km'],
            },
        ),
        migrations.CreateModel(
            name='FixedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_name', models.CharField(max_length=255, verbose_name='Route Name')),
                ('pickup_address', models.CharField(max_length=500, verbose_name='Pickup Address')),
                ('pickup_lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Pickup Latitude')),
                ('pickup_lng', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Pickup Longitude')),
                ('pickup_type', models.CharField(choices=[('airport', 'Airport'), ('city_center', 'City Center'), ('hotel_zone', 'Hotel Zone'), ('resort', 'Resort'), ('exact_address', 'Exact Address')], default='city_center', max_length=20, verbose_name='Pickup Type')),
                ('pickup_radius_km', models.DecimalField(decimal_places=2, default=2.0, help_text='Tolerance radius for matching', max_digits=5, verbose_name='Pickup Radius (km)')),
                ('dropoff_address', models.CharField(max_length=500, verbose_name='Dropoff Address')),
                ('dropoff_lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Dropoff Latitude')),
                ('dropoff_lng', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Dropoff Longitude')),
                ('dropoff_type', models.CharField(choices=[('airport', 'Airport'), ('city_center', 'City Center'), ('hotel_zone', 'Hotel Zone'), ('resort', 'Resort'), ('exact_address', 'Exact Address')], default='city_center', max_length=20, verbose_name='Dropoff Type')),
                ('dropoff_radius_km', models.DecimalField(decimal_places=2, default=2.0, help_text='Tolerance radius for matching', max_digits=5, verbose_name='Dropoff Radius (km)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Price (EUR)')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Pre-calculated route distance', max_digits=10, null=True, verbose_name='Distance (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'Fixed Route',
                'verbose_name_plural': 'Fixed Routes',
                'ordering': ['route_name'],
            },
        ),
    ]
