# Generated by Django 5.0.7 on 2026-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('de', 'Deutsch'), ('fr', 'Français'), ('ar', 'العربية')], default='en', max_length=5, verbose_name='Preferred Language'),
        ),
    ]
