# Generated by Django 5.2 on 2026-01-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_language_field'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_plate', models.CharField(max_length=20, verbose_name='Vehicle Plate')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Vehicle Model')),
                ('vehicle_color', models.CharField(blank=True, max_length=50, verbose_name='Vehicle Color')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('vehicle_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicleclass', verbose_name='Vehicle Class')),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
            },
        ),
    ]
