# Generated by Django 5.0.7 on 2026-01-18 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=100, verbose_name='Class Name')),
                ('class_code', models.CharField(max_length=50, unique=True, verbose_name='Class Code')),
                ('tier_level', models.PositiveIntegerField(help_text='1 = lowest (Economy), higher = premium', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Tier Level')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='1.00 = base price, 1.30 = +30%', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price Multiplier')),
                ('max_passengers', models.PositiveIntegerField(verbose_name='Max Passengers')),
                ('max_large_luggage', models.PositiveIntegerField(verbose_name='Max Large Luggage')),
                ('max_small_luggage', models.PositiveIntegerField(verbose_name='Max Small Luggage')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('example_vehicles', models.CharField(blank=True, help_text='e.g., "Mercedes E-Class, BMW 5 Series"', max_length=255, verbose_name='Example Vehicles')),
                ('icon_url', models.URLField(blank=True, verbose_name='Icon URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Vehicle Class',
                'verbose_name_plural': 'Vehicle Classes',
                'ordering': ['tier_level', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='VehicleClassRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_value', models.PositiveIntegerField(verbose_name='Minimum Value')),
                ('max_value', models.PositiveIntegerField(verbose_name='Maximum Value')),
                ('min_vehicle_tier', models.PositiveIntegerField(help_text='Minimum tier required for this range', verbose_name='Minimum Vehicle Tier')),
                ('required_for', models.CharField(choices=[('passengers', 'Passengers'), ('luggage', 'Luggage'), ('both', 'Both')], default='passengers', max_length=20, verbose_name='Requirement Type')),
                ('is_strict', models.BooleanField(default=True, help_text='If true, cannot be downgraded', verbose_name='Strict Requirement')),
                ('validation_message', models.CharField(blank=True, help_text='Message shown when requirement not met', max_length=255, verbose_name='Validation Message')),
            ],
            options={
                'verbose_name': 'Vehicle Requirement',
                'verbose_name_plural': 'Vehicle Requirements',
                'ordering': ['required_for', 'min_value'],
            },
        ),
    ]
